config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :locations
  resources :prices
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :location
  validates :firstname, :lastname, :telephone, :email, :registration_number, :location, presence: true
  
  def self.search(search)
    where("firstname LIKE ? OR lastname LIKE ? OR telephone LIKE ? OR email LIKE ? OR make LIKE ? OR model LIKE ? OR registration_number LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_many :bookings, dependent: :destroy
    validates :title, presence: true
    validates :title, uniqueness: true
end

app/models/price.rb
class Price < ActiveRecord::Base
    validates :title, presence: true
    validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_location, only: [:new, :create]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
    if params[:search]
      @bookings = Booking.search(params[:search]).order("created_at DESC")
    else
      @bookings = Booking.all.order('created_at DESC')
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = @location.bookings.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = @location.bookings.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:location_id, :firstname, :lastname, :telephone, :email, :make, :model, :registration_number, :duration)
    end
    
    def set_location
      @location = Location.find_by(id: params[:location_id]) || Location.find(booking_params[:location_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end
  
  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
    ContactMailer.contact_email(email, name, telephone, message).deliver_now
    flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
  redirect_to root_path
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :description)
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render :show, status: :created, location: @price }
      else
        format.html { render :new }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { render :show, status: :ok, location: @price }
      else
        format.html { render :edit }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url, notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/bookings/_form.html.haml
= form_for @booking do |f|
  - if @booking.errors.any?
    #error_explanation
      %h2= "#{pluralize(@booking.errors.count, "error")} prohibited this booking from being saved:"
      %ul
        - @booking.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :location
    %p= @booking.location.description
    = f.hidden_field :location_id, value: @booking.location.id
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :telephone
    = f.number_field :telephone
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :make
    = f.text_field :make
  .field
    = f.label :model
    = f.text_field :model
  .field
    = f.label :registration_number
    = f.text_field :registration_number
  .field
    = f.label :duration
    = f.text_field :duration
  .actions
    = f.submit 'Save'

app/views/bookings/edit.html.haml
%h1 Editing booking

= render 'form'

= link_to 'Show', @booking
\|
= link_to 'Back', bookings_path

app/views/bookings/index.html.haml
%h1 Listing bookings

= form_tag bookings_path, method: 'get' do
  = label_tag :search, t('.search')
  = text_field_tag :search, '', title: t('.enter_a_search')
  
  = submit_tag t('.search')
  
- if @bookings.present?
  - render @bookings
- else
  %p There are no bookings with that description

%table
  %thead
    %tr
      %th Location
      %th Firstname
      %th Lastname
      %th Telephone
      %th Email
      %th Make
      %th Model
      %th Registration number
      %th Duration
      %th
      %th
      %th

  %tbody
    - @bookings.each do |booking|
      %tr
        %td= booking.location.description
        %td= booking.firstname
        %td= booking.lastname
        %td= booking.telephone
        %td= booking.email
        %td= booking.make
        %td= booking.model
        %td= booking.registration_number
        %td= booking.duration

%br

app/views/bookings/new.html.haml
%h1 New booking

= render 'form'

= link_to 'Back', bookings_path

app/views/bookings/show.html.haml
%p#notice= notice

%p
  %b Location:
  = @booking.location.description
%p
  %b Firstname:
  = @booking.firstname
%p
  %b Lastname:
  = @booking.lastname
%p
  %b Telephone:
  = @booking.telephone
%p
  %b Email:
  = @booking.email
%p
  %b Make:
  = @booking.make
%p
  %b Model:
  = @booking.model
%p
  %b Registration number:
  = @booking.registration_number
%p
  %b duration:
  = @booking.duration

= link_to 'Back', bookings_path

app/views/home/contact.html.haml
%h1= t('.title')
.pc= t('.contact_us')

= form_tag request_contact_path, method: 'post' do
    = label_tag :name, t('.name')
    = text_field_tag :name, '', title: t('.enter_name'), size: 50
    
    = label_tag :email, t('.email')
    = email_field_tag :email, '', title: t('.enter_email')
    
    = label_tag :telephone, t('.telephone')
    = telephone_field_tag :telephone, '', title: t('.enter_telephone')
    
    = label_tag :message, t('.message')
    = text_field_tag :message, '', title: t('.enter_message'), size: 100
    
    = submit_tag t('.submit')

app/views/home/home.html.haml
%h1= t('.title')
.p1= t('.welcome')
.p2= t('.paragraph2')
.p3= t('.paragraph3')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
  
    -flash.each do |key, value|
      = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

    = render 'shared/header'

    = yield
    
    = render 'shared/footer'

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %thead
    %tr
      %th Title
      %th Description
      %th 
      %th
      %th

  %tbody
    - @locations.each do |location|
      %tr
        %td= location.title
        %td= location.description
        %td
        %td= link_to 'Show', location

%br

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @location.title
%p
  %b Description:
  = @location.description
  
%p= link_to 'Add Booking', new_booking_path(location_id: @location)

= link_to 'Back', locations_path

app/views/prices/_form.html.haml
= form_for @price do |f|
  - if @price.errors.any?
    #error_explanation
      %h2= "#{pluralize(@price.errors.count, "error")} prohibited this price from being saved:"
      %ul
        - @price.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/prices/edit.html.haml
%h1 Editing price

= render 'form'

= link_to 'Show', @price
\|
= link_to 'Back', prices_path

app/views/prices/index.html.haml
%h1 Listing prices

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Cost in £s
      %th
      %th
      %th

  %tbody
    - @prices.each do |price|
      %tr
        %td= price.title
        %td= price.description
        %td= price.cost

%br

app/views/prices/new.html.haml
%h1 New price

= render 'form'

= link_to 'Back', prices_path

app/views/prices/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @price.title
%p
  %b Description:
  = @price.description

= link_to 'Edit', edit_price_path(@price)
\|
= link_to 'Back', prices_path

app/views/shared/_footer.html.haml
%footer
    %p Created by Piers Wareham

app/views/shared/_header.html.haml
%div.nav
    %ul
        %li
            = link_to 'Home', root_path
        %li
            = link_to 'Prices', prices_path
        %li    
            = link_to 'Parking Locations', locations_path
        %li    
            = link_to 'Bookings', bookings_path 
        %li
            = link_to 'Contact Us', contact_path